export CRAIGLY_EMAIL_SMTP_HOST=[redacted]
export CRAIGLY_EMAIL_SMTP_PORT=[redacted]
export CRAIGLY_EMAIL_SMTP_USER=[redacted]
export CRAIGLY_EMAIL_SMTP_PASS=[redacted]
export CRAIGLY_EMAIL_SMTP_FROM=[redacted]
export CRAIGLY_EMAIL_ERROR_TO_ADDRESS=[redacted]